//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Bot.Builder.Skills.Contextual.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RelationshipStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RelationshipStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Bot.Builder.Skills.Contextual.Resources.RelationshipStrings", typeof(RelationshipStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aunt | aunts.
        /// </summary>
        public static string Aunt {
            get {
                return ResourceManager.GetString("Aunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brother | brothers.
        /// </summary>
        public static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brother_in_law | brother in law | brother-in-law.
        /// </summary>
        public static string Brother_In_Law {
            get {
                return ResourceManager.GetString("Brother_In_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to child | children | kids.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colleague | colleagues.
        /// </summary>
        public static string Colleague {
            get {
                return ResourceManager.GetString("Colleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cousin | cousins.
        /// </summary>
        public static string Cousin {
            get {
                return ResourceManager.GetString("Cousin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daughter | daughters.
        /// </summary>
        public static string Daughter {
            get {
                return ResourceManager.GetString("Daughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daughter in law | daughter-in-law.
        /// </summary>
        public static string Daughter_In_Law {
            get {
                return ResourceManager.GetString("Daughter_In_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dad | father.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to father in law | father-in-law.
        /// </summary>
        public static string Father_In_Law {
            get {
                return ResourceManager.GetString("Father_In_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend | friends.
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandchild | grandchildren.
        /// </summary>
        public static string Grandchild {
            get {
                return ResourceManager.GetString("Grandchild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to granddaughter.
        /// </summary>
        public static string Granddaughter {
            get {
                return ResourceManager.GetString("Granddaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandfather | grandpa.
        /// </summary>
        public static string Grandfather {
            get {
                return ResourceManager.GetString("Grandfather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandma | grandmother.
        /// </summary>
        public static string Grandmother {
            get {
                return ResourceManager.GetString("Grandmother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandparent | grandparents.
        /// </summary>
        public static string Grandparent {
            get {
                return ResourceManager.GetString("Grandparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandson | grandsons.
        /// </summary>
        public static string Grandson {
            get {
                return ResourceManager.GetString("Grandson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to husband.
        /// </summary>
        public static string Husband {
            get {
                return ResourceManager.GetString("Husband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boss | manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mom | mother.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mother_in_law.
        /// </summary>
        public static string Mother_in_law {
            get {
                return ResourceManager.GetString("Mother_in_law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neighbor | neighbors.
        /// </summary>
        public static string Neighbor {
            get {
                return ResourceManager.GetString("Neighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nephew.
        /// </summary>
        public static string Nephew {
            get {
                return ResourceManager.GetString("Nephew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to niece.
        /// </summary>
        public static string Niece {
            get {
                return ResourceManager.GetString("Niece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parent | parents.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sibling | siblings.
        /// </summary>
        public static string Sibling {
            get {
                return ResourceManager.GetString("Sibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sister | sisters.
        /// </summary>
        public static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sister in law | sister-in-law.
        /// </summary>
        public static string Sister_In_Law {
            get {
                return ResourceManager.GetString("Sister_In_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to son | sons.
        /// </summary>
        public static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to son in law | son-in-law.
        /// </summary>
        public static string Son_In_Law {
            get {
                return ResourceManager.GetString("Son_In_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step daughter | step-daughter.
        /// </summary>
        public static string Step_Daughter {
            get {
                return ResourceManager.GetString("Step_Daughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepfather.
        /// </summary>
        public static string Stepfather {
            get {
                return ResourceManager.GetString("Stepfather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepmother.
        /// </summary>
        public static string Stepmother {
            get {
                return ResourceManager.GetString("Stepmother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepsister.
        /// </summary>
        public static string Stepsister {
            get {
                return ResourceManager.GetString("Stepsister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepson.
        /// </summary>
        public static string Stepson {
            get {
                return ResourceManager.GetString("Stepson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to student | students.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teacher | teachers.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncle | uncles.
        /// </summary>
        public static string Uncle {
            get {
                return ResourceManager.GetString("Uncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wife.
        /// </summary>
        public static string Wife {
            get {
                return ResourceManager.GetString("Wife", resourceCulture);
            }
        }
    }
}
