const ENABLE_SPEECH = 'ENABLE_SPEECH';
const ENABLE_SPEECH_PENDING = `${ ENABLE_SPEECH }_PENDING`;
const ENABLE_SPEECH_REJECTED = `${ ENABLE_SPEECH }_REJECTED`;
const ENABLE_SPEECH_FULFILLED = `${ ENABLE_SPEECH }_FULFILLED`;

export {
  ENABLE_SPEECH_PENDING,
  ENABLE_SPEECH_REJECTED,
  ENABLE_SPEECH_FULFILLED
}
