// <auto-generated>
// Code generated by LUISGen C:\Users\darrenj\Downloads\restaurantbookingdj1en_reservation (1).json -cs Luis.Reservation -o C:\Users\darrenj\Downloads
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public class Reservation: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            None, 
            Reservation
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] people;

            // Built-in entities
            public DateTimeSpec[] datetime;
            public string[] geographyV2_City;
            public double[] number;

            // Lists
            public string[][] cuisine;

            // Composites
            public class _Instanceattendees
            {
                public InstanceData[] number;
                public InstanceData[] people;
            }
            public class attendeesClass
            {
                public double[] number;
                public string[] people;
                [JsonProperty("$instance")]
                public _Instanceattendees _instance;
            }
            public attendeesClass[] attendees;

            // Instance
            public class _Instance
            {
                public InstanceData[] people;
                public InstanceData[] datetime;
                public InstanceData[] geography;
                public InstanceData[] number;
                public InstanceData[] cuisine;
                public InstanceData[] attendees;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<Reservation>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
