# specific branch build
trigger:
  branches:  
    include:
    - master
    - feature/*

  paths:
    include:
    - 'lib/csharp/microsoft.bot.builder.skills/*'

# By default will disable PR builds
pr: none

pool:
   name: Hosted VS2017
   demands:
    - msbuild
    - visualstudio

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.100'
  inputs:
    version: 2.2.100
  continueOnError: true

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.1'
  inputs:
    versionSpec: 4.9.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'lib\csharp\Microsoft.Bot.Builder.Skills.sln'

- task: VSBuild@1
  displayName: 'Build solution Microsoft.Bot.Builder.Skills.sln'
  inputs:
    solution: lib\csharp\Microsoft.Bot.Builder.Skills.sln
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'test results'
  inputs:
    command: test
    projects: '$(System.DefaultWorkingDirectory)\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills.Tests\Microsoft.Bot.Builder.Skills.Tests.csproj'
    arguments: '-v n --configuration $(buildConfiguration) --no-build --no-restore --filter TestCategory!=IgnoreInAutomatedBuild /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    workingDirectory: 'lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills.Tests'
   
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills.Tests\coverage.cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills.Tests'