// <auto-generated>
// Code generated by LUISGen
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public class CalendarLU: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            AcceptEventEntry,
            ChangeCalendarEntry,
            CheckAvailability,
            ConnectToMeeting, 
            ContactMeetingAttendees, 
            CreateCalendarEntry, 
            DeleteCalendarEntry, 
            FindCalendarDetail, 
            FindCalendarEntry, 
            FindCalendarWhen, 
            FindCalendarWhere, 
            FindCalendarWho, 
            FindDuration, 
            FindMeetingRoom, 
            GoBack, 
            None, 
            ShowNextCalendar,
            ShowPreviousCalendar,
            TimeRemaining
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] DestinationCalendar;
            public string[] Duration;
            public string[] ToDate;
            public string[] ToTime;
            public string[] Location;
            public string[] MeetingRoom;
            public string[] Message;
            public string[] MoveEarlierTimeSpan;
            public string[] MoveLaterTimeSpan;
            public string[] OrderReference;
            public string[] PositionReference;
            public string[] SlotAttribute;
            public string[] FromDate;
            public string[] FromTime;
            public string[] Subject;

            // Built-in entities
            public string[] personName;
            public double[] number;
            public double[] ordinal;
            public DateTimeSpec[] datetime;

            // Instance
            public class _Instance
            {
                public InstanceData[] DestinationCalendar;
                public InstanceData[] Duration;
                public InstanceData[] ToDate;
                public InstanceData[] ToTime;
                public InstanceData[] Location;
                public InstanceData[] MeetingRoom;
                public InstanceData[] Message;
                public InstanceData[] MoveEarlierTimeSpan;
                public InstanceData[] MoveLaterTimeSpan;
                public InstanceData[] OrderReference;
                public InstanceData[] PositionReference;
                public InstanceData[] SlotAttribute;
                public InstanceData[] FromDate;
                public InstanceData[] FromTime;
                public InstanceData[] Subject;

                public InstanceData[] personName;
                public InstanceData[] number;
                public InstanceData[] ordinal;
                public InstanceData[] datetime;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<CalendarLU>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
