//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupportTemplate.Dialogs.Returns.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerSupportTemplate.Dialogs.Returns.Resources.ReturnStrings", typeof(ReturnStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to an agent.
        /// </summary>
        public static string ExchangeTypeAgent {
            get {
                return ResourceManager.GetString("ExchangeTypeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to process the exchange in the store or with a customer service agent?.
        /// </summary>
        public static string ExchangeTypePrompt {
            get {
                return ResourceManager.GetString("ExchangeTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In store.
        /// </summary>
        public static string ExchangeTypeStore {
            get {
                return ResourceManager.GetString("ExchangeTypeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am happy to help. Can you provide the order number?.
        /// </summary>
        public static string OrderNumberPrompt {
            get {
                return ResourceManager.GetString("OrderNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand that order number. Your order number is a 7 digit code that can be found in your order confirmation email..
        /// </summary>
        public static string OrderNumberReprompt {
            get {
                return ResourceManager.GetString("OrderNumberReprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great. I found the refund. Can you please verify the phone number associated with the account?.
        /// </summary>
        public static string PhoneNumberPrompt {
            get {
                return ResourceManager.GetString("PhoneNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand that. Please enter a valid phone number including the area code (ex. (800) 555-1234)..
        /// </summary>
        public static string PhoneNumberReprompt {
            get {
                return ResourceManager.GetString("PhoneNumberReprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.  Here is your refund status:.
        /// </summary>
        public static string RefundStatusMessage {
            get {
                return ResourceManager.GetString("RefundStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like me to find an agent to help you process a return?.
        /// </summary>
        public static string StartReturnPrompt {
            get {
                return ResourceManager.GetString("StartReturnPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your zip code?.
        /// </summary>
        public static string ZipCodePrompt {
            get {
                return ResourceManager.GetString("ZipCodePrompt", resourceCulture);
            }
        }
    }
}
