/**
* <auto-generated>
* Code generated by LUISGen C:\Users\MartinBattaglino\Desktop\dispatch.json -ts General -o C:\Git\AI\solutions\Virtual-Assistant\src\typescript\bot-solutions\src\resources
* Tool github: https://github.com/microsoft/botbuilder-tools
* Changes may cause incorrect behavior and will be lost if the code is
* regenerated.
* </auto-generated>
*/ 
import {DateTimeSpec, IntentData, InstanceData, NumberWithUnits} from 'botbuilder-ai';

export interface _Intents { 
    l_General: IntentData;
    q_FAQ: IntentData;
    Greeting: IntentData;
    Help: IntentData;
    Cancel: IntentData;
    Restart: IntentData;
    Escalate: IntentData;
    Next: IntentData;
    Previous: IntentData;
    Goodbye: IntentData;
    Logout: IntentData;
    None: IntentData;
};

export interface _Instance {
    datetime?: InstanceData[];
    number?: InstanceData[];
}

export interface _Entities {

    // Built-in entities
    datetime?: DateTimeSpec[];
    number?: number[];
    $instance : _Instance;
}

export interface General {
    text: string;
    alteredText?: string;
    intents: _Intents;
    entities: _Entities;
    [propName: string]: any;
}
