/**
* <auto-generated>
* Code generated by LUISGen C:\SW-Projects\ai\solutions\Virtual-Assistant\src\typescript\assistant\deploymentScripts\..\LocaleConfigurations\..\deploymentScripts\en\sample.luis -ts sampleLU -o C:\SW-Projects\ai\solutions\Virtual-Assistant\src\typescript\assistant\deploymentScripts\..\LocaleConfigurations\..\..\skills\sampleSkill\cognitiveModels\LUIS\en\sample.lu\..\..\..\..\src\dialogs\shared\resources
* Tool github: https://github.com/microsoft/botbuilder-tools
* Changes may cause incorrect behavior and will be lost if the code is
* regenerated.
* </auto-generated>
*/ 
import {DateTimeSpec, IntentData, InstanceData, NumberWithUnits} from 'botbuilder-ai';

export interface _Intents { 
    Sample: IntentData;
    None: IntentData;
};

export interface _Instance {
}

export interface _Entities {
    $instance : _Instance;
}

export interface sampleLU {
    text: string;
    alteredText?: string;
    intents: _Intents;
    entities: _Entities;
    [propName: string]: any;
}
