/**
* <auto-generated>
* Code generated by LUISGen D:\bmw_workspace\wa-search-skill\deployment\Resources\LU\wa-search-skill\en\waSearchSkill.luis -ts waSearchSkillLuis -o D:\bmw_workspace\wa-search-skill\src\services
* Tool github: https://github.com/microsoft/botbuilder-tools
* Changes may cause incorrect behavior and will be lost if the code is
* regenerated.
* </auto-generated>
*/ 
import {GeographyV2, IntentData, InstanceData} from 'botbuilder-ai';

export interface _Intents { 
    CallPerson: IntentData;
    MessagePerson: IntentData;
    None: IntentData;
    SearchPeople: IntentData;
    SearchProxy: IntentData;
    SearchResponsible: IntentData;
    SelectItem: IntentData;
    ShowNext: IntentData;
    ShowPrevious: IntentData;
};

export interface _Instance {
    DepartmentCode?: InstanceData[];
    DirectionalReference?: InstanceData[];
    PersonName?: InstanceData[];
    geographyV2?: InstanceData[];
    jobDescription?: InstanceData[];
    jobTitle?: InstanceData[];
    number?: InstanceData[];
    ordinal?: InstanceData[];
}

export interface _Entities {
    // Simple entities
    DepartmentCode?: string[];
    DirectionalReference?: string[];
    PersonName?: string[];
    jobDescription?: string[];
    jobTitle?: string[];

    // Built-in entities
    geographyV2?: GeographyV2[];

    number?: number[];

    ordinal?: number[];
    $instance : _Instance;
}

export interface waSearchSkillLuis {
    text: string;
    alteredText?: string;
    intents: _Intents;
    entities: _Entities;
    [propName: string]: any;
}
