pool:
  vmImage: 'windows-2019'
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio

variables:
  system.debug: false
  # AzureDevOpsServicePrincipalSecret: Secret of the Service Principal
  # AzureSubscription: Name of your Azure Subscription
  # AzureTenant: Tenant's value of your Azure directory
  # BotBuilderPackageVersion: Version of the BotBuilder package
  # BotLanguages: The supported languages of your bot
  # BuildConfiguration: Build configuration such as Debug or Release
  # BuildPlatform: Build platform such as Win32, x86, x64 or any cpu
  # endpoints.0.endpointUrl: Skill Manifest endpoint url
  # endpoints.0.msAppId: Skill Manifest Microsoft App Id
  # Location: Location of the bot
  # LuisAuthoringRegion: Location of the LUIS apps
  # ServicePrincipal: App Id of the Service Principal
  # SkillBotAppId: Microsoft App Id of the Skill bot
  # SkillBotAppPassword: Microsoft App Password of the Skill bot
  # SkillBotName: Name of the Skill bot
  # system.debug: System variable that can be set by the users. Set this to true to run the release in debug mode to assist in fault-finding.
  # VirtualAssistantBotAppId: Microsoft App Id of the Virtual Assistant bot
  # VirtualAssistantBotAppPassword: Microsoft App Password of the Virtual Assistant bot
  # VirtualAssistantBotName: Name of the Virtual Assistant bot

jobs:
- job: VirtualAssistant
  timeoutInMinutes: 0
  dependsOn: Skill
  variables:
    BotAppId: $(VirtualAssistantBotAppId)
    BotAppPassword: $(VirtualAssistantBotAppPassword)
    BotName: $(VirtualAssistantBotName)
    DependenciesPath: 'samples/csharp/assistants/virtual-assistant/**/*.csproj'
    FunctionalTestProject: 'samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.sln'
    RegexReplace: '$1$(BotBuilderPackageVersion)'
    RegexSearch: '("Microsoft\.Bot\.(?!Solutions|Connector.DirectLine)\S+"\s)(Version="\S*")'
    SolutionName: 'VirtualAssistantSample.sln'
    SolutionPath: 'samples/csharp/assistants/virtual-assistant/'
    WorkingDirectory: 'samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/'
    SKILLBOTWEBAPPURL: $[ dependencies.Skill.outputs['skillDeploy.SKILLBOTWEBAPPURL'] ]
  steps:
  - template: ../../../../../yaml/cleanupResourcesStep.yml
  - template: ../../../../../yaml/useNodeStep.yml
  - template: ../../../../../yaml/useNugetStep.yml
  - template: ../../../../../yaml/npmInstallRequirementsStep.yml
  - template: ../../../../../yaml/dotnetLogVersionsStep.yml
  - template: ../../../../../yaml/setConfigFileStep.yml
  - template: ../../../../../yaml/dotnetBuildStep.yml
  - template: ../../../../../yaml/deployStep.yml

  - pwsh: |
     $appsettings = Get-Content -Path "appsettings.json" | Out-String | ConvertFrom-Json

     Write-Output $appSettings

     $botWebAppName = $appsettings.botWebAppName
     $resourceGroupName= $appsettings.resourceGroupName

     Write-Host "VA Web App Name"
     Write-Host "===="
     Write-Host $botWebAppName
     Write-Host "`r`n"
     echo "##vso[task.setvariable variable=BOTWEBAPPNAME;]$botWebAppName"

     Write-Host "VA Resource Group"
     Write-Host "===="
     Write-Host $resourceGroupName
     echo "##vso[task.setvariable variable=BOTRESOURCEGROUP;]$resourceGroupName"
    workingDirectory: 'samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/'
    displayName: 'Deploy: VA - Get bot variables from appsettings'
    failOnStderr: true

  - pwsh: |
     $skillManifestUrl = "https://$(SKILLBOTWEBAPPURL)/manifest/manifest-1.1.json"

     Write-Host "Skill Manifest"
     Write-Host "===="
     Write-Host $skillManifestUrl
     Write-Host "`r`n"

     botskills connect --remoteManifest "$skillManifestUrl" --luisFolder '..\..\..\skill\SkillSample\Deployment\Resources\LU\' --cs --languages 'en-us' --noRefresh --verbose

     botskills refresh --cs --verbose

    workingDirectory: 'samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/'
    displayName: 'Test: VA - Connect SkillSample'
    failOnStderr: false

  - task: DotNetCoreCLI@2
    displayName: 'Build: VA - Build project'
    inputs:
      projects: 'samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.sln'
      arguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site" /property:langversion=latest'
      workingDirectory: 'samples/csharp/assistants/virtual-assistant/'

  - pwsh: '.\Deployment\Scripts\publish.ps1 -name "$(BOTWEBAPPNAME)" -resourceGroup "$(BOTRESOURCEGROUP)"'
    errorActionPreference: continue
    workingDirectory: 'samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/'
    displayName: 'Test: VA - Publish with connected Skill'
    failOnStderr: true

  - template: ../../../../../yaml/setDirectLineStep.yml

  - powershell: |
     $json = Get-Content "DirectLineCreate.json" | Out-String | ConvertFrom-Json
     $key = $json.properties.properties.sites.key

     Write-Host "Direct Line key"
     Write-Host "===="
     Write-Host "$key"
     Write-Host "`r`n"

     echo "##vso[task.setvariable variable=DIRECTLINE;]$key"


     Write-Host "Bot name"
     Write-Host "===="
     Write-Host "DirectLine Bot Name: $(BotName)"
     Write-Host "`r`n"

     echo "##vso[task.setvariable variable=BOTID;]$(BotName)"

    workingDirectory: 'samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/'
    displayName: 'Test: VA - Get channel secrets'
    failOnStderr: true

  - template: ../../../../../yaml/functionalTestsStep.yml
  - template: ../../../../../yaml/cleanupResourcesStep.yml
  - template: ../../../../../yaml/endLogStep.yml

  - script: 'dir ..\*.* /s'
    displayName: 'Debug: dir workspace'
    continueOnError: true
    condition: always()

- job: Skill
  timeoutInMinutes: 0

  variables:
    BotAppId: $(SkillBotAppId)
    BotAppPassword: $(SkillBotAppPassword)
    BotName: $(SkillBotName)
    DependenciesPath: 'samples/csharp/skill/**/*.csproj'
    FunctionalTestProject: 'samples/csharp/skill/SkillSample.sln'
    RegexReplace: '$1$(BotBuilderPackageVersion)'
    RegexSearch: '("Microsoft\.Bot\.(?!Solutions|Connector.DirectLine)\S+"\s)(Version="\S*")'
    SolutionName: 'SkillSample.sln'
    SolutionPath: 'samples/csharp/skill/'
    WorkingDirectory: 'samples/csharp/skill/SkillSample'
  steps:
  - template: ../../../../../yaml/cleanupResourcesStep.yml
  - template: ../../../../../yaml/useNodeStep.yml
  - template: ../../../../../yaml/useNugetStep.yml
  - template: ../../../../../yaml/npmInstallRequirementsStep.yml
  - template: ../../../../../yaml/dotnetLogVersionsStep.yml
  - template: ../../../../../yaml/setConfigFileStep.yml

  - task: FileTransform@1
    displayName: 'Prepare: Replace Skill manifest properties'
    inputs:
      folderPath: samples/csharp/skill/
      fileType: json
      targetFiles: |
       **/wwwroot/manifest/manifest-1.1.json
       **/wwwroot/manifest/manifest-1.0.json

  - template: ../../../../../yaml/dotnetBuildStep.yml
  - template: ../../../../../yaml/deployStep.yml

  - pwsh: |
     $appsettings = Get-Content -Path "appsettings.json" | Out-String | ConvertFrom-Json

     Write-Output $appSettings

     $botWebAppName = $appsettings.botWebAppName
     $resourceGroupName= $appsettings.resourceGroupName
     $url = "$botWebAppName.azurewebsites.net"

     Write-Host "Skill Web App Name"
     Write-Host "===="
     Write-Host $botWebAppName
     echo "##vso[task.setvariable variable=BOTWEBAPPNAME;]$botWebAppName"

     Write-Host "URL"
     Write-Host "===="
     Write-Host $url
     echo "##vso[task.setvariable variable=SKILLBOTWEBAPPURL;isOutput=true]$url"

     Write-Host "Skill Resource Group"
     Write-Host "===="
     Write-Host $resourceGroupName
     echo "##vso[task.setvariable variable=BOTRESOURCEGROUP;]$resourceGroupName"
    workingDirectory: samples/csharp/skill/SkillSample
    displayName: 'Deploy: Skill - Get bot variables from appsettings'
    name: 'skillDeploy'
    failOnStderr: false

  - template: ../../../../../yaml/setDirectLineStep.yml

  - powershell: |
     $json = Get-Content "DirectLineCreate.json" | Out-String | ConvertFrom-Json
     $key = $json.properties.properties.sites.key

     Write-Host "Direct Line key"
     Write-Host "===="
     Write-Host "$key"
     Write-Host "`r`n"

     echo "##vso[task.setvariable variable=DIRECTLINE;]$key"

     Write-Host "Bot name"
     Write-Host "===="
     Write-Host "DirectLine Bot Name: $(BOTWEBAPPNAME)"
     Write-Host "`r`n"

     echo "##vso[task.setvariable variable=BOTID;]$(BOTWEBAPPNAME)"
    workingDirectory: samples/csharp/skill/SkillSample
    displayName: 'Test: Skill - Get channel secrets'
    failOnStderr: true

  - template: ../../../../../yaml/functionalTestsStep.yml
  - template: ../../../../../yaml/endLogStep.yml
