const CONNECT_PENDING = 'CONNECT_PENDING';
const CONNECT_REJECTED = 'CONNECT_REJECTED';
const CONNECT_FULFILLED = 'CONNECT_FULFILLED';

export {
  CONNECT_PENDING,
  CONNECT_REJECTED,
  CONNECT_FULFILLED
}
