// <auto-generated>
// Code generated by LUISGen
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
namespace LuisModelTest.Models
{
    public class LuisResult
    {
        [JsonProperty("query")]
        public string Query { get; set; }

        [JsonProperty("topScoringIntent")]
        public IntentResult TopScoringIntent { get; set; }

        [JsonProperty("intents")]
        public List<IntentResult> Intents { get; set; }

        [JsonProperty("entities")]
        public List<EntityResult> Entities { get; set; }

        public class IntentResult
        {
            [JsonProperty("intent")]
            public string Intent { get; set; }

            [JsonProperty("score")]
            public double Score { get; set; }
        }

        public class EntityResult
        {
            [JsonProperty("entity")]
            public string Entity { get; set; }

            [JsonProperty("type")]
            public string Type { get; set; }

            [JsonProperty("startIndex")]
            public int StartIndex { get; set; }

            [JsonProperty("endIndex")]
            public int EndIndex { get; set; }

            [JsonProperty("score")]
            public double? Score { get; set; }
        }
    }
}
