//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoSkill.Dialogs.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToDoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToDoStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoSkill.Dialogs.Shared.Resources.ToDoStrings", typeof(ToDoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and {0}. .
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refer to the link {0} to see the lists created for you..
        /// </summary>
        public static string EmailContent {
            get {
                return ResourceManager.GetString("EmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists are created for you.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery.
        /// </summary>
        public static string Grocery {
            get {
                return ResourceManager.GetString("Grocery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grocery, groceries, grocer.
        /// </summary>
        public static string GrocerySynonym {
            get {
                return ResourceManager.GetString("GrocerySynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Notebook.
        /// </summary>
        public static string OneNoteBookName {
            get {
                return ResourceManager.GetString("OneNoteBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Section.
        /// </summary>
        public static string OneNoteSectionName {
            get {
                return ResourceManager.GetString("OneNoteSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shopping.
        /// </summary>
        public static string ShoppingSynonym {
            get {
                return ResourceManager.GetString("ShoppingSynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do.
        /// </summary>
        public static string ToDo {
            get {
                return ResourceManager.GetString("ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to do, todo, to-do, to dos, todos. to-dos, to - do.
        /// </summary>
        public static string ToDoSynonym {
            get {
                return ResourceManager.GetString("ToDoSynonym", resourceCulture);
            }
        }
    }
}
