//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarSkill.Dialogs.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarSkill.Dialogs.Shared.Resources.BotStrings", typeof(BotStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afternoon.
        /// </summary>
        public static string Afternoon {
            get {
                return ResourceManager.GetString("Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/en.
        /// </summary>
        public static string AssetsDir {
            get {
                return ResourceManager.GetString("AssetsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to battery.
        /// </summary>
        public static string battery {
            get {
                return ResourceManager.GetString("battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body chassis.
        /// </summary>
        public static string bodychassis {
            get {
                return ResourceManager.GetString("bodychassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body type.
        /// </summary>
        public static string bodytype {
            get {
                return ResourceManager.GetString("bodytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Concierge.
        /// </summary>
        public static string CallConcierge {
            get {
                return ResourceManager.GetString("CallConcierge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2 emission.
        /// </summary>
        public static string co2emission {
            get {
                return ResourceManager.GetString("co2emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compression ratio.
        /// </summary>
        public static string compressionratio {
            get {
                return ResourceManager.GetString("compressionratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drive transmission.
        /// </summary>
        public static string drivetransmission {
            get {
                return ResourceManager.GetString("drivetransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty weight.
        /// </summary>
        public static string emptyweight {
            get {
                return ResourceManager.GetString("emptyweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evening.
        /// </summary>
        public static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front brakes.
        /// </summary>
        public static string frontbrakes {
            get {
                return ResourceManager.GetString("frontbrakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front brake diameter.
        /// </summary>
        public static string frontbreakdiameter {
            get {
                return ResourceManager.GetString("frontbreakdiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front track.
        /// </summary>
        public static string fronttrack {
            get {
                return ResourceManager.GetString("fronttrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front wheel suspension.
        /// </summary>
        public static string frontwheelsuspension {
            get {
                return ResourceManager.GetString("frontwheelsuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel consumption.
        /// </summary>
        public static string fuelconsumption {
            get {
                return ResourceManager.GetString("fuelconsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel induction system.
        /// </summary>
        public static string fuelinductionsystem {
            get {
                return ResourceManager.GetString("fuelinductionsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gearbox ratios.
        /// </summary>
        public static string gearboxratios {
            get {
                return ResourceManager.GetString("gearboxratios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmwenglishindexv2.
        /// </summary>
        public static string KnowledgeGraphAzureSearchIndex {
            get {
                return ResourceManager.GetString("KnowledgeGraphAzureSearchIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum speed.
        /// </summary>
        public static string maximumspeed {
            get {
                return ResourceManager.GetString("maximumspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me more.
        /// </summary>
        public static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to morning.
        /// </summary>
        public static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} people.
        /// </summary>
        public static string People_MoreThanOne {
            get {
                return ResourceManager.GetString("People_MoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} person.
        /// </summary>
        public static string People_One {
            get {
                return ResourceManager.GetString("People_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permissible total weight.
        /// </summary>
        public static string permissibletotalweight {
            get {
                return ResourceManager.GetString("permissibletotalweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power output.
        /// </summary>
        public static string poweroutput {
            get {
                return ResourceManager.GetString("poweroutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product title.
        /// </summary>
        public static string producttitle {
            get {
                return ResourceManager.GetString("producttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rear brakes.
        /// </summary>
        public static string rearbrakes {
            get {
                return ResourceManager.GetString("rearbrakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rear track.
        /// </summary>
        public static string reartrack {
            get {
                return ResourceManager.GetString("reartrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rear wheel suspension.
        /// </summary>
        public static string rearwheelsuspension {
            get {
                return ResourceManager.GetString("rearwheelsuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference title.
        /// </summary>
        public static string referencetitle {
            get {
                return ResourceManager.GetString("referencetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reverse gear.
        /// </summary>
        public static string reversegear {
            get {
                return ResourceManager.GetString("reversegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spark plugs.
        /// </summary>
        public static string sparkplugs {
            get {
                return ResourceManager.GetString("sparkplugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, MMMM dd.
        /// </summary>
        public static string SpokenDateFormat {
            get {
                return ResourceManager.GetString("SpokenDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SpokenDatePrefix {
            get {
                return ResourceManager.GetString("SpokenDatePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type of engine.
        /// </summary>
        public static string typeofengine {
            get {
                return ResourceManager.GetString("typeofengine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Memo.
        /// </summary>
        public static string VoiceMemoTitle {
            get {
                return ResourceManager.GetString("VoiceMemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s a transcription of your note.
        /// </summary>
        public static string VoiceMemoTranscription {
            get {
                return ResourceManager.GetString("VoiceMemoTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wheel rims.
        /// </summary>
        public static string wheelrims {
            get {
                return ResourceManager.GetString("wheelrims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
