sudo: required

language: node_js

node_js:
- "11"

services:
- docker

before_install:
- npm ci
- sudo apt-get install jq
- npx version-from-git --travis
- git checkout -b temp-ci
- lerna version --exact --force-publish --no-git-tag-version --no-push --yes `cat package.json | jq -r .version`

install:
- docker-compose build

script:
- echo

deploy:
- provider: script
  script: bash scripts/docker_push
  on:
    branch: master
