// <auto-generated>
// Code generated by LUISGen C:\Users\lamil\Source\Repos\botframework-solutions\samples\AdaptiveAssistant\AdaptiveAssistant\Deployment\Scripts\..\Resources\Dispatch\en\LamilAdaptiveAssistanten_Dispatch.json -cs Luis.DispatchLuis -o C:\Users\lamil\Source\Repos\botframework-solutions\samples\AdaptiveAssistant\AdaptiveAssistant\Services
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class DispatchLuis: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            l_General, 
            q_Chitchat, 
            q_Faq, 
            pointOfInterestSkill, 
            newsSkill, 
            calendarSkill, 
            None
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] KEYWORD;
            public string[] ADDRESS;
            public string[] topic;
            public string[] site;
            public string[] Subject;
            public string[] FromDate;
            public string[] FromTime;
            public string[] ToTime;
            public string[] ToDate;
            public string[] Message;

            // Built-in entities
            public string[] personName;

            // Instance
            public class _Instance
            {
                public InstanceData[] KEYWORD;
                public InstanceData[] ADDRESS;
                public InstanceData[] topic;
                public InstanceData[] site;
                public InstanceData[] Subject;
                public InstanceData[] FromDate;
                public InstanceData[] FromTime;
                public InstanceData[] ToTime;
                public InstanceData[] ToDate;
                public InstanceData[] Message;
                public InstanceData[] personName;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<DispatchLuis>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
