//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantBooking.Dialogs.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestaurantBooking.Dialogs.Shared.Resources.BotStrings", typeof(BotStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afternoon.
        /// </summary>
        internal static string Afternoon {
            get {
                return ResourceManager.GetString("Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/en.
        /// </summary>
        internal static string AssetsDir {
            get {
                return ResourceManager.GetString("AssetsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to battery.
        /// </summary>
        internal static string battery {
            get {
                return ResourceManager.GetString("battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body chassis.
        /// </summary>
        internal static string bodychassis {
            get {
                return ResourceManager.GetString("bodychassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body type.
        /// </summary>
        internal static string bodytype {
            get {
                return ResourceManager.GetString("bodytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Concierge.
        /// </summary>
        internal static string CallConcierge {
            get {
                return ResourceManager.GetString("CallConcierge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2 emission.
        /// </summary>
        internal static string co2emission {
            get {
                return ResourceManager.GetString("co2emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compression ratio.
        /// </summary>
        internal static string compressionratio {
            get {
                return ResourceManager.GetString("compressionratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Concierge Services Inc..
        /// </summary>
        internal static string ConciergeAgentCompany {
            get {
                return ResourceManager.GetString("ConciergeAgentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am your simulated concierge agent. Say &quot;QUIT&quot; to hang up..
        /// </summary>
        internal static string ConciergeAgentMessage {
            get {
                return ResourceManager.GetString("ConciergeAgentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        internal static string ConciergeAgentName {
            get {
                return ResourceManager.GetString("ConciergeAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, We&apos;re all set. Here&apos;s the spa appointment you requested:.
        /// </summary>
        internal static string ConciergeBookedSpaAppointment {
            get {
                return ResourceManager.GetString("ConciergeBookedSpaAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drive transmission.
        /// </summary>
        internal static string drivetransmission {
            get {
                return ResourceManager.GetString("drivetransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty weight.
        /// </summary>
        internal static string emptyweight {
            get {
                return ResourceManager.GetString("emptyweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evening.
        /// </summary>
        internal static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front brakes.
        /// </summary>
        internal static string frontbrakes {
            get {
                return ResourceManager.GetString("frontbrakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front brake diameter.
        /// </summary>
        internal static string frontbreakdiameter {
            get {
                return ResourceManager.GetString("frontbreakdiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front track.
        /// </summary>
        internal static string fronttrack {
            get {
                return ResourceManager.GetString("fronttrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front wheel suspension.
        /// </summary>
        internal static string frontwheelsuspension {
            get {
                return ResourceManager.GetString("frontwheelsuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel consumption.
        /// </summary>
        internal static string fuelconsumption {
            get {
                return ResourceManager.GetString("fuelconsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel induction system.
        /// </summary>
        internal static string fuelinductionsystem {
            get {
                return ResourceManager.GetString("fuelinductionsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gearbox ratios.
        /// </summary>
        internal static string gearboxratios {
            get {
                return ResourceManager.GetString("gearboxratios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knowledgegraphindex.
        /// </summary>
        internal static string KnowledgeGraphAzureSearchIndex {
            get {
                return ResourceManager.GetString("KnowledgeGraphAzureSearchIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Has Requested A Loaner Vehicle. Follow Up With Customer As Soon As Possible..
        /// </summary>
        internal static string LoanerCarMessage {
            get {
                return ResourceManager.GetString("LoanerCarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum speed.
        /// </summary>
        internal static string maximumspeed {
            get {
                return ResourceManager.GetString("maximumspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save your note..
        /// </summary>
        internal static string MemoSaveFail {
            get {
                return ResourceManager.GetString("MemoSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your note was saved in the {0} section with title: &apos;{1}&apos;..
        /// </summary>
        internal static string MemoSaveSuccess {
            get {
                return ResourceManager.GetString("MemoSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Memos section was not found in your Notebook, expected to find a section named &apos;{0}&apos;.
        /// </summary>
        internal static string MemoSectionNotFound {
            get {
                return ResourceManager.GetString("MemoSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me more.
        /// </summary>
        internal static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to morning.
        /// </summary>
        internal static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} people.
        /// </summary>
        internal static string People_MoreThanOne {
            get {
                return ResourceManager.GetString("People_MoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} person.
        /// </summary>
        internal static string People_One {
            get {
                return ResourceManager.GetString("People_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permissible total weight.
        /// </summary>
        internal static string permissibletotalweight {
            get {
                return ResourceManager.GetString("permissibletotalweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power output.
        /// </summary>
        internal static string poweroutput {
            get {
                return ResourceManager.GetString("poweroutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product title.
        /// </summary>
        internal static string producttitle {
            get {
                return ResourceManager.GetString("producttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Next.
        /// </summary>
        internal static string ShowNext {
            get {
                return ResourceManager.GetString("ShowNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Previous.
        /// </summary>
        internal static string ShowPrevious {
            get {
                return ResourceManager.GetString("ShowPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spark plugs.
        /// </summary>
        internal static string sparkplugs {
            get {
                return ResourceManager.GetString("sparkplugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, MMMM dd.
        /// </summary>
        internal static string SpokenDateFormat {
            get {
                return ResourceManager.GetString("SpokenDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpokenDatePrefix {
            get {
                return ResourceManager.GetString("SpokenDatePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
