//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarSkill.Dialogs.Shared.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalendarCommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarCommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarSkill.Dialogs.Shared.Resources.Strings.CalendarCommonStrings", typeof(CalendarCommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (adjust|change|update)?.*(content|body|detail|details).
        /// </summary>
        public static string AdjustContent {
            get {
                return ResourceManager.GetString("AdjustContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (adjust|change|update)?.*(duration|length).
        /// </summary>
        public static string AdjustDuration {
            get {
                return ResourceManager.GetString("AdjustDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (adjust|change|update)?.*(location|place|where).
        /// </summary>
        public static string AdjustLocation {
            get {
                return ResourceManager.GetString("AdjustLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (adjust|change|update|add|delete)?.*(participants|attendee|attendees|people|person).
        /// </summary>
        public static string AdjustParticipants {
            get {
                return ResourceManager.GetString("AdjustParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (adjust|change|update)?.*(subject|title).
        /// </summary>
        public static string AdjustSubject {
            get {
                return ResourceManager.GetString("AdjustSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (adjust|change|update)?.*time.
        /// </summary>
        public static string AdjustTime {
            get {
                return ResourceManager.GetString("AdjustTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        public static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all day.
        /// </summary>
        public static string AllDayLower {
            get {
                return ResourceManager.GetString("AllDayLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} more.
        /// </summary>
        public static string AttendeesSummary {
            get {
                return ResourceManager.GetString("AttendeesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0}.
        /// </summary>
        public static string AtTime {
            get {
                return ResourceManager.GetString("AtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before.
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(no|cancel|nop|don&apos;t|not).
        /// </summary>
        public static string CancelAdjust {
            get {
                return ResourceManager.GetString("CancelAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,|and|;.
        /// </summary>
        public static string ContactSeparator {
            get {
                return ResourceManager.GetString("ContactSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily.
        /// </summary>
        public static string DailyToken {
            get {
                return ResourceManager.GetString("DailyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half an hour.
        /// </summary>
        public static string HalfAnHour {
            get {
                return ResourceManager.GetString("HalfAnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly.
        /// </summary>
        public static string MonthlyToken {
            get {
                return ResourceManager.GetString("MonthlyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(me|myself)$.
        /// </summary>
        public static string Myself {
            get {
                return ResourceManager.GetString("Myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no attendees.
        /// </summary>
        public static string NoAttendees {
            get {
                return ResourceManager.GetString("NoAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}nd.
        /// </summary>
        public static string OrdinalSuffixNd {
            get {
                return ResourceManager.GetString("OrdinalSuffixNd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}rd.
        /// </summary>
        public static string OrdinalSuffixRd {
            get {
                return ResourceManager.GetString("OrdinalSuffixRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}st.
        /// </summary>
        public static string OrdinalSuffixSt {
            get {
                return ResourceManager.GetString("OrdinalSuffixSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}th.
        /// </summary>
        public static string OrdinalSuffixTh {
            get {
                return ResourceManager.GetString("OrdinalSuffixTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(skip|no).
        /// </summary>
        public static string SkipPhrases {
            get {
                return ResourceManager.GetString("SkipPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string TodayLower {
            get {
                return ResourceManager.GetString("TodayLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string TomorrowLower {
            get {
                return ResourceManager.GetString("TomorrowLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekly.
        /// </summary>
        public static string WeeklyToken {
            get {
                return ResourceManager.GetString("WeeklyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a subject of {0}.
        /// </summary>
        public static string WithTheSubject {
            get {
                return ResourceManager.GetString("WithTheSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string YesterdayLower {
            get {
                return ResourceManager.GetString("YesterdayLower", resourceCulture);
            }
        }
    }
}
