//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfInterestSkillTests.Flow.Utterances {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PointOfInterestDialogUtterances {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PointOfInterestDialogUtterances() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PointOfInterestSkillTests.Flow.Utterances.PointOfInterestDialogUtterances", typeof(PointOfInterestDialogUtterances).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /event:{ &quot;Name&quot;: &quot;IPA.ActiveLocation&quot;, &quot;Value&quot;: &quot;Microsoft Corporation&quot;,&quot;Text&quot;:&quot;find a route&quot; }.
        /// </summary>
        internal static string ActiveLocationEvent {
            get {
                return ResourceManager.GetString("ActiveLocationEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel my route.
        /// </summary>
        internal static string CancelRoute {
            get {
                return ResourceManager.GetString("CancelRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find a parking garage near 1635 11th Ave.
        /// </summary>
        internal static string FindParkingNearAddress {
            get {
                return ResourceManager.GetString("FindParkingNearAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find a parking garage.
        /// </summary>
        internal static string FindParkingNearby {
            get {
                return ResourceManager.GetString("FindParkingNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find a coffee shop.
        /// </summary>
        internal static string FindPointOfInterest {
            get {
                return ResourceManager.GetString("FindPointOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get directions to microsoft corporation.
        /// </summary>
        internal static string GetDirectionsByName {
            get {
                return ResourceManager.GetString("GetDirectionsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get directions to the pharmacy.
        /// </summary>
        internal static string GetDirectionsByNewName {
            get {
                return ResourceManager.GetString("GetDirectionsByNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found the following matches..
        /// </summary>
        internal static string IFoundTheFollowingMatches {
            get {
                return ResourceManager.GetString("IFoundTheFollowingMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /event:{ &quot;Name&quot;: &quot;IPA.Location&quot;, &quot;Value&quot;: &quot;47.639620,-122.130610&quot; }.
        /// </summary>
        internal static string LocationEvent {
            get {
                return ResourceManager.GetString("LocationEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What else can I help you with?.
        /// </summary>
        internal static string WhatElseCanIHelpYouWith {
            get {
                return ResourceManager.GetString("WhatElseCanIHelpYouWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s nearby?.
        /// </summary>
        internal static string WhatsNearby {
            get {
                return ResourceManager.GetString("WhatsNearby", resourceCulture);
            }
        }
    }
}
