// <auto-generated>
// Code generated by LUISGen
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class HospitalityLuis: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            CheckOut, 
            ExtendStay, 
            GetReservationDetails, 
            LateCheckOut, 
            None, 
            RequestItem, 
            RoomService
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] HotelNights;
            public string[] Item;
            public string[] SpecialRequest;
            public string[] Food;

            // Built-in entities
            public DateTimeSpec[] datetime;
            public double[] number;

            // Lists
            public string[][] Menu;

            // Composites
            public class _InstanceFoodRequest
            {
                public InstanceData[] number;
                public InstanceData[] Food;
                public InstanceData[] SpecialRequest;
            }
            public class FoodRequestClass
            {
                public double[] number;
                public string[] Food;
                public string[] SpecialRequest;
                [JsonProperty("$instance")]
                public _InstanceFoodRequest _instance;
            }
            public FoodRequestClass[] FoodRequest;

            public class _InstanceItemRequest
            {
                public InstanceData[] number;
                public InstanceData[] Item;
            }
            public class ItemRequestClass
            {
                public double[] number;
                public string[] Item;
                [JsonProperty("$instance")]
                public _InstanceItemRequest _instance;
            }
            public ItemRequestClass[] ItemRequest;

            public class _InstanceNumNights
            {
                public InstanceData[] number;
                public InstanceData[] HotelNights;
            }
            public class NumNightsClass
            {
                public double[] number;
                public string[] HotelNights;
                [JsonProperty("$instance")]
                public _InstanceNumNights _instance;
            }
            public NumNightsClass[] NumNights;

            // Instance
            public class _Instance
            {
                public InstanceData[] HotelNights;
                public InstanceData[] Item;
                public InstanceData[] SpecialRequest;
                public InstanceData[] Food;
                public InstanceData[] datetime;
                public InstanceData[] number;
                public InstanceData[] Menu;
                public InstanceData[] FoodRequest;
                public InstanceData[] ItemRequest;
                public InstanceData[] NumNights;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<HospitalityLuis>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
