# specific branch build
trigger:
  branches:  
    include:
    - master
    - feature/*

  paths:
    include:
    - 'lib/typescript/botbuilder-skills/*'
  
# By default will disable PR builds
pr: none

pool:
  vmImage: 'vs2017-win2016'
steps:
- task: NodeTool@0
  displayName: 'Use Node 10.'
  inputs:
    versionSpec: 10.x

- pwsh: 'node ./common/scripts/install-run-rush.js install --no-link'
  workingDirectory: lib/typescript
  displayName: 'rush install'

- pwsh: 'node ./common/scripts/install-run-rush.js link'
  workingDirectory: lib/typescript
  displayName: 'rush link'

- pwsh: 'node ./common/scripts/install-run-rush.js build'
  workingDirectory: lib/typescript
  displayName: 'rush build'

- pwsh: 'node ./common/scripts/install-run-rush.js test-coverage-ci'
  errorActionPreference: continue
  ignoreLASTEXITCODE: 'true'
  workingDirectory: lib/typescript
  displayName: 'rush test coverage'

- task: PublishTestResults@2
  displayName: 'publish test results'
  inputs:
    testResultsFiles: 'test-results.xml'
    searchFolder: 'lib/typescript/botbuilder-skills'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'lib/typescript/botbuilder-skills/coverage/cobertura-coverage.xml'
    reportDirectory: 'lib/typescript/botbuilder-skills/coverage/'
