# specific branch build
trigger:
  branches:  
    include:
    - master
    - feature/*

  paths:
    include:
    - 'templates/Virtual-Assistant-Template/typescript/samples/sample-skill/*'

# By default will disable PR builds
pr: none

pool:
  name: Hosted VS2017
  demands: npm
steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'templates/Virtual-Assistant-Template/typescript/samples/sample-skill'
    verbose: false

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: 'templates/Virtual-Assistant-Template/typescript/samples/sample-skill'
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'test with coverage'
  inputs:
    command: custom
    workingDir: 'templates/Virtual-Assistant-Template/typescript/samples/sample-skill'
    verbose: false
    customCommand: 'run test-coverage-ci'

- task: PublishTestResults@2
  displayName: 'publish test results'
  inputs:
    testResultsFiles: 'test-results.xml'
    searchFolder: 'templates/Virtual-Assistant-Template/typescript/samples/sample-skill'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: 'publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'templates/Virtual-Assistant-Template/typescript/samples/sample-skill/coverage/cobertura-coverage.xml'
    reportDirectory: 'templates/Virtual-Assistant-Template/typescript/samples/sample-skill/coverage/'

