/**
* <auto-generated>
* Code generated by LUISGen C:\SW-Projects\ai\solutions\Virtual-Assistant\src\typescript\assistant\deploymentScripts\..\LocaleConfigurations\..\deploymentScripts\en\general.luis -ts GeneralLU -o C:\SW-Projects\ai\solutions\Virtual-Assistant\src\typescript\assistant\deploymentScripts\..\LocaleConfigurations\..\CognitiveModels\LUIS\en\general.lu\..\..\..\..\src\dialogs\shared\resources
* Tool github: https://github.com/microsoft/botbuilder-tools
* Changes may cause incorrect behavior and will be lost if the code is
* regenerated.
* </auto-generated>
*/ 
import {DateTimeSpec, IntentData, InstanceData, NumberWithUnits} from 'botbuilder-ai';

export interface _Intents { 
    Greeting: IntentData;
    Help: IntentData;
    Cancel: IntentData;
    Restart: IntentData;
    Escalate: IntentData;
    Next: IntentData;
    Previous: IntentData;
    Goodbye: IntentData;
    Logout: IntentData;
    None: IntentData;
};

export interface _Instance {
    datetime?: InstanceData[];
    number?: InstanceData[];
}

export interface _Entities {

    // Built-in entities
    datetime?: DateTimeSpec[];
    number?: number[];
    $instance : _Instance;
}

export interface GeneralLU {
    text: string;
    alteredText?: string;
    intents: _Intents;
    entities: _Entities;
    [propName: string]: any;
}
