//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarSkill.Dialogs.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarSkill.Dialogs.Shared.Resources.BotImages", typeof(BotImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/assistant-logo.jpg.
        /// </summary>
        public static string AssistantLogo {
            get {
                return ResourceManager.GetString("AssistantLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/car-genius.png.
        /// </summary>
        public static string CarGenius {
            get {
                return ResourceManager.GetString("CarGenius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/concierge.jpg.
        /// </summary>
        public static string Concierge {
            get {
                return ResourceManager.GetString("Concierge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/cuisines/chinese.jpg.
        /// </summary>
        public static string CuisinesChinese {
            get {
                return ResourceManager.GetString("CuisinesChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/cuisines/german.jpg.
        /// </summary>
        public static string CuisinesGerman {
            get {
                return ResourceManager.GetString("CuisinesGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/cuisines/indian.jpg.
        /// </summary>
        public static string CuisinesIndian {
            get {
                return ResourceManager.GetString("CuisinesIndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/cuisines/italian.jpg.
        /// </summary>
        public static string CuisinesItalian {
            get {
                return ResourceManager.GetString("CuisinesItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faq/blank.gif.
        /// </summary>
        public static string FaqBlank {
            get {
                return ResourceManager.GetString("FaqBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faq/BreakFluidRed.png.
        /// </summary>
        public static string FaqBreakFluidRed {
            get {
                return ResourceManager.GetString("FaqBreakFluidRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faq/BreakFluidYellow.png.
        /// </summary>
        public static string FaqBreakFluidYellow {
            get {
                return ResourceManager.GetString("FaqBreakFluidYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faq/TirePressureRed.png.
        /// </summary>
        public static string FaqTirePressureRed {
            get {
                return ResourceManager.GetString("FaqTirePressureRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faq/TirePressureYellow.png.
        /// </summary>
        public static string FaqTirePressureYellow {
            get {
                return ResourceManager.GetString("FaqTirePressureYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/in-car-productivity.png.
        /// </summary>
        public static string InCarProductivity {
            get {
                return ResourceManager.GetString("InCarProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/microsoft/office365.png.
        /// </summary>
        public static string MicrosoftOffice365 {
            get {
                return ResourceManager.GetString("MicrosoftOffice365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spa/plus.png.
        /// </summary>
        public static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productivity/calendar.png.
        /// </summary>
        public static string ProductivityCalendar {
            get {
                return ResourceManager.GetString("ProductivityCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productivity/calendar-black.png.
        /// </summary>
        public static string ProductivityCalendarBlack {
            get {
                return ResourceManager.GetString("ProductivityCalendarBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productivity/todo.png.
        /// </summary>
        public static string ProductivityTodo {
            get {
                return ResourceManager.GetString("ProductivityTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productivity/todo-black.png.
        /// </summary>
        public static string ProductivityTodoBlack {
            get {
                return ResourceManager.GetString("ProductivityTodoBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/push-to-talk.png.
        /// </summary>
        public static string PushToTalk {
            get {
                return ResourceManager.GetString("PushToTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/bamboo-garden.jpg.
        /// </summary>
        public static string RestaurantsBambooGarden {
            get {
                return ResourceManager.GetString("RestaurantsBambooGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/biryani-house.jpg.
        /// </summary>
        public static string RestaurantsBiryaniHouse {
            get {
                return ResourceManager.GetString("RestaurantsBiryaniHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/chens.jpg.
        /// </summary>
        public static string RestaurantsChens {
            get {
                return ResourceManager.GetString("RestaurantsChens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/euro-bistro.jpg.
        /// </summary>
        public static string RestaurantsEuroBistro {
            get {
                return ResourceManager.GetString("RestaurantsEuroBistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/german-gourmet.jpg.
        /// </summary>
        public static string RestaurantsGermanGourmet {
            get {
                return ResourceManager.GetString("RestaurantsGermanGourmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/kanishka-cuisine.jpg.
        /// </summary>
        public static string RestaurantsKanishkaCuisine {
            get {
                return ResourceManager.GetString("RestaurantsKanishkaCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/maharani-inside.jpg.
        /// </summary>
        public static string RestaurantsMaharaniInside {
            get {
                return ResourceManager.GetString("RestaurantsMaharaniInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/mamma-mia-pizza.jpg.
        /// </summary>
        public static string RestaurantsMammaMiaPizza {
            get {
                return ResourceManager.GetString("RestaurantsMammaMiaPizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/mandarin.jpg.
        /// </summary>
        public static string RestaurantsMandarin {
            get {
                return ResourceManager.GetString("RestaurantsMandarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/the-bavarian.jpg.
        /// </summary>
        public static string RestaurantsTheBavarian {
            get {
                return ResourceManager.GetString("RestaurantsTheBavarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/tonys.jpg.
        /// </summary>
        public static string RestaurantsTonys {
            get {
                return ResourceManager.GetString("RestaurantsTonys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants/tuscani-grill.jpg.
        /// </summary>
        public static string RestaurantsTuscaniGrill {
            get {
                return ResourceManager.GetString("RestaurantsTuscaniGrill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceScheduling/oil-change.jpg.
        /// </summary>
        public static string ServiceSchedulingOilChange {
            get {
                return ResourceManager.GetString("ServiceSchedulingOilChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/smart-interior.png.
        /// </summary>
        public static string SmartInterior {
            get {
                return ResourceManager.GetString("SmartInterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spa/spa.jpg.
        /// </summary>
        public static string Spa {
            get {
                return ResourceManager.GetString("Spa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/welcome-aboard.png.
        /// </summary>
        public static string WelcomeAboard {
            get {
                return ResourceManager.GetString("WelcomeAboard", resourceCulture);
            }
        }
    }
}
