// <auto-generated>
// Code generated by LUISGen .\Deployment\Resources\Dispatch\en\ConnectedCarAssistanten_Dispatch.json -cs Luis.DispatchLuis -o C:\Users\rylengel\source\repos\AI\templates\Virtual-Assistant-Template\csharp\Sample\VirtualAssistantSample\Services
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class DispatchLuis: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            BingSearchSkill, 
            calendarSkill, 
            emailSkill, 
            l_general, 
            newsSkill, 
            pointOfInterestSkill, 
            q_chitchat, 
            q_faq, 
            toDoSkill, 
            None
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] ADDRESS;
            public string[] KEYWORD;
            public string[] address;
            public string[] topic;

            // Pattern.any
            public string[] keyword;
            public string[] TaskContentPattern;
            public string[] ShopContent;
            public string[] CelebrityNamePatten;
            public string[] MovieTitlePatten;

            // Instance
            public class _Instance
            {
                public InstanceData[] ADDRESS;
                public InstanceData[] KEYWORD;
                public InstanceData[] address;
                public InstanceData[] topic;
                public InstanceData[] keyword;
                public InstanceData[] TaskContentPattern;
                public InstanceData[] ShopContent;
                public InstanceData[] CelebrityNamePatten;
                public InstanceData[] MovieTitlePatten;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<DispatchLuis>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
