# Knom RegexReplace task https://marketplace.visualstudio.com/items?itemName=knom.regexreplace-task

steps:
  - task: knom.regexreplace-task.regex-replace.RegexReplace@3
    displayName: 'Prepare: Update SDK to latest preview version'
    inputs:
      InputSearchPattern: $(DependenciesPath)
      FindRegex: $(RegexSearch)
      ReplaceRegex: $(RegexReplace)
