// <auto-generated>
// Code generated by LUISGen C:\Users\lamil\Source\Repos\AI\experimental\AdaptiveAssistant\AdaptiveAssistant\Deployment\Resources\Dispatch\en\LamilAssistanten_Dispatch.json -cs Luis.DispatchLuis -o C:\Users\lamil\Source\Repos\AI\experimental\AdaptiveAssistant\AdaptiveAssistant\Services
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class DispatchLuis: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            l_general, 
            q_chitchat, 
            q_faq, 
            calendarSkill, 
            emailSkill, 
            toDoSkill, 
            pointOfInterestSkill, 
            None
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] DirectionalReference;
            public string[] Subject;
            public string[] FromDate;
            public string[] FromTime;
            public string[] ToTime;
            public string[] ToDate;
            public string[] Message;
            public string[] OrderReference;
            public string[] SenderName;
            public string[] Category;
            public string[] ContactName;
            public string[] EmailSubject;
            public string[] ListType;
            public string[] TaskContent;
            public string[] ADDRESS;
            public string[] KEYWORD;

            // Built-in entities
            public double[] number;
            public double[] ordinal;
            public string[] personName;

            // Lists
            public string[][] FoodOfGrocery;

            // Pattern.any
            public string[] Message_Any;
            public string[] EmailSubject_Any;
            public string[] SearchTexts_Any;
            public string[] TaskContent_Any;
            public string[] keyword;

            // Instance
            public class _Instance
            {
                public InstanceData[] DirectionalReference;
                public InstanceData[] Subject;
                public InstanceData[] FromDate;
                public InstanceData[] FromTime;
                public InstanceData[] ToTime;
                public InstanceData[] ToDate;
                public InstanceData[] Message;
                public InstanceData[] OrderReference;
                public InstanceData[] SenderName;
                public InstanceData[] Category;
                public InstanceData[] ContactName;
                public InstanceData[] EmailSubject;
                public InstanceData[] ListType;
                public InstanceData[] TaskContent;
                public InstanceData[] ADDRESS;
                public InstanceData[] KEYWORD;
                public InstanceData[] number;
                public InstanceData[] ordinal;
                public InstanceData[] personName;
                public InstanceData[] FoodOfGrocery;
                public InstanceData[] Message_Any;
                public InstanceData[] EmailSubject_Any;
                public InstanceData[] SearchTexts_Any;
                public InstanceData[] TaskContent_Any;
                public InstanceData[] keyword;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<DispatchLuis>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
