//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSMSkill.Responses.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITSMSkill.Responses.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string AttributeDescription {
            get {
                return ResourceManager.GetString("AttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string AttributeId {
            get {
                return ResourceManager.GetString("AttributeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        public static string AttributeNumber {
            get {
                return ResourceManager.GetString("AttributeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        public static string AttributeState {
            get {
                return ResourceManager.GetString("AttributeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urgency.
        /// </summary>
        public static string AttributeUrgency {
            get {
                return ResourceManager.GetString("AttributeUrgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Go forward/previous&quot; to navigate..
        /// </summary>
        public static string GoBoth {
            get {
                return ResourceManager.GetString("GoBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Go forward&quot; to navigate..
        /// </summary>
        public static string GoForward {
            get {
                return ResourceManager.GetString("GoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Go previous&quot; to navigate..
        /// </summary>
        public static string GoPrevious {
            get {
                return ResourceManager.GetString("GoPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID: .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened at .
        /// </summary>
        public static string OpenedAt {
            get {
                return ResourceManager.GetString("OpenedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Article.
        /// </summary>
        public static string OpenKnowledge {
            get {
                return ResourceManager.GetString("OpenKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by **{0}**.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TicketActionCloseTitle {
            get {
                return ResourceManager.GetString("TicketActionCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close the ticket {0}.
        /// </summary>
        public static string TicketActionCloseValue {
            get {
                return ResourceManager.GetString("TicketActionCloseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string TicketActionUpdateTitle {
            get {
                return ResourceManager.GetString("TicketActionUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update the ticket {0}.
        /// </summary>
        public static string TicketActionUpdateValue {
            get {
                return ResourceManager.GetString("TicketActionUpdateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number: .
        /// </summary>
        public static string TicketNumber {
            get {
                return ResourceManager.GetString("TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: .
        /// </summary>
        public static string TicketState {
            get {
                return ResourceManager.GetString("TicketState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string TicketStateCanceled {
            get {
                return ResourceManager.GetString("TicketStateCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string TicketStateClosed {
            get {
                return ResourceManager.GetString("TicketStateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string TicketStateInProgress {
            get {
                return ResourceManager.GetString("TicketStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string TicketStateNew {
            get {
                return ResourceManager.GetString("TicketStateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hold.
        /// </summary>
        public static string TicketStateOnHold {
            get {
                return ResourceManager.GetString("TicketStateOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string TicketStateResolved {
            get {
                return ResourceManager.GetString("TicketStateResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated at .
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgency: .
        /// </summary>
        public static string Urgency {
            get {
                return ResourceManager.GetString("Urgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string UrgencyHigh {
            get {
                return ResourceManager.GetString("UrgencyHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string UrgencyLow {
            get {
                return ResourceManager.GetString("UrgencyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string UrgencyMedium {
            get {
                return ResourceManager.GetString("UrgencyMedium", resourceCulture);
            }
        }
    }
}
