// <auto-generated>
// Code generated by LUISGen vehiclesettings_change_confirmation.json -cs Luis.VehicleSettingsChangeConfirmation -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public class VehicleSettingsChangeConfirmation: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            None, 
            SETTING_CHANGE_CONFIRMATION_NO, 
            SETTING_CHANGE_CONFIRMATION_YES
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] VALUE;
            public string[] AMOUNT;
            public string[] UNIT;
            public string[] SETTING;
            public string[] INDEX;
            public string[] TYPE;

            // Instance
            public class _Instance
            {
                public InstanceData[] VALUE;
                public InstanceData[] AMOUNT;
                public InstanceData[] UNIT;
                public InstanceData[] SETTING;
                public InstanceData[] INDEX;
                public InstanceData[] TYPE;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<VehicleSettingsChangeConfirmation>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
